const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const {Pool}=require('pg');

const PORT=Number(process.env.PORT||3000);
const TEACHER_PASSWORD=process.env.TEACHER_PASSWORD||'minoo123';
const DATABASE_URL=process.env.DATABASE_URL||'';
const usePostgres=Boolean(DATABASE_URL);
let sqlite,pool;

function makeCode(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='MIN-';for(let i=0;i<6;i++)s+=a[crypto.randomInt(a.length)];return s}
async function initDb(){
 if(usePostgres){
  pool=new Pool({connectionString:DATABASE_URL,ssl:{rejectUnauthorized:false}});
  await pool.query(`
   CREATE TABLE IF NOT EXISTS classes(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL UNIQUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
   CREATE TABLE IF NOT EXISTS students(id BIGSERIAL PRIMARY KEY,class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,name TEXT NOT NULL,code TEXT NOT NULL UNIQUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
   CREATE TABLE IF NOT EXISTS games(id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,canva_url TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
   CREATE TABLE IF NOT EXISTS assignments(id BIGSERIAL PRIMARY KEY,game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),completed_at TIMESTAMPTZ,UNIQUE(game_id,student_id));
   ALTER TABLE students ADD COLUMN IF NOT EXISTS guardian_name TEXT;
   ALTER TABLE students ADD COLUMN IF NOT EXISTS guardian_phone TEXT;
   ALTER TABLE students ADD COLUMN IF NOT EXISTS photo_data TEXT;
   ALTER TABLE students ADD COLUMN IF NOT EXISTS teacher_note TEXT;
   ALTER TABLE students ADD COLUMN IF NOT EXISTS username TEXT;
   ALTER TABLE students ADD COLUMN IF NOT EXISTS password_hash TEXT;
   ALTER TABLE students ADD COLUMN IF NOT EXISTS password_changed BOOLEAN NOT NULL DEFAULT FALSE;
   CREATE UNIQUE INDEX IF NOT EXISTS students_username_unique ON students(username) WHERE username IS NOT NULL;
   ALTER TABLE games ADD COLUMN IF NOT EXISTS game_type TEXT NOT NULL DEFAULT 'external';
   ALTER TABLE games ADD COLUMN IF NOT EXISTS game_data TEXT;
   CREATE TABLE IF NOT EXISTS parent_notes(id BIGSERIAL PRIMARY KEY,student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,note TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),seen_at TIMESTAMPTZ);
   CREATE TABLE IF NOT EXISTS meal_records(id BIGSERIAL PRIMARY KEY,student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,record_date DATE NOT NULL,meal TEXT NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(student_id,record_date,meal));
   CREATE TABLE IF NOT EXISTS game_attempts(id BIGSERIAL PRIMARY KEY,assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,first_score INTEGER NOT NULL DEFAULT 0,total INTEGER NOT NULL DEFAULT 0,retries INTEGER NOT NULL DEFAULT 0,duration_seconds INTEGER NOT NULL DEFAULT 0,stars INTEGER NOT NULL DEFAULT 0,completed BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
   CREATE TABLE IF NOT EXISTS teachers(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
   CREATE TABLE IF NOT EXISTS teacher_classes(teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,PRIMARY KEY(teacher_id,class_id));
  `);
 }else{
  sqlite=new DatabaseSync(path.join(__dirname,'minoo.db')); sqlite.exec(`PRAGMA foreign_keys=ON;
   CREATE TABLE IF NOT EXISTS classes(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
   CREATE TABLE IF NOT EXISTS students(id INTEGER PRIMARY KEY AUTOINCREMENT,class_id INTEGER NOT NULL REFERENCES classes(id) ON DELETE CASCADE,name TEXT NOT NULL,code TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
   CREATE TABLE IF NOT EXISTS games(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,canva_url TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
   CREATE TABLE IF NOT EXISTS assignments(id INTEGER PRIMARY KEY AUTOINCREMENT,game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,assigned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at TEXT,UNIQUE(game_id,student_id));`);
  const cols=sqlite.prepare('PRAGMA table_info(students)').all().map(x=>x.name);
  if(!cols.includes('guardian_name')) sqlite.exec('ALTER TABLE students ADD COLUMN guardian_name TEXT');
  if(!cols.includes('guardian_phone')) sqlite.exec('ALTER TABLE students ADD COLUMN guardian_phone TEXT');
  if(!cols.includes('photo_data')) sqlite.exec('ALTER TABLE students ADD COLUMN photo_data TEXT');
  if(!cols.includes('teacher_note')) sqlite.exec('ALTER TABLE students ADD COLUMN teacher_note TEXT');
  if(!cols.includes('username')) sqlite.exec('ALTER TABLE students ADD COLUMN username TEXT');
  if(!cols.includes('password_hash')) sqlite.exec('ALTER TABLE students ADD COLUMN password_hash TEXT');
  if(!cols.includes('password_changed')) sqlite.exec('ALTER TABLE students ADD COLUMN password_changed INTEGER NOT NULL DEFAULT 0');
  sqlite.exec('CREATE UNIQUE INDEX IF NOT EXISTS students_username_unique ON students(username) WHERE username IS NOT NULL');
  const gcols=sqlite.prepare('PRAGMA table_info(games)').all().map(x=>x.name);
  if(!gcols.includes('game_type')) sqlite.exec("ALTER TABLE games ADD COLUMN game_type TEXT NOT NULL DEFAULT 'external'");
  if(!gcols.includes('game_data')) sqlite.exec('ALTER TABLE games ADD COLUMN game_data TEXT');
  sqlite.exec(`CREATE TABLE IF NOT EXISTS parent_notes(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,note TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,seen_at TEXT); CREATE TABLE IF NOT EXISTS meal_records(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,record_date TEXT NOT NULL,meal TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(student_id,record_date,meal)); CREATE TABLE IF NOT EXISTS game_attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,assignment_id INTEGER NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,first_score INTEGER NOT NULL DEFAULT 0,total INTEGER NOT NULL DEFAULT 0,retries INTEGER NOT NULL DEFAULT 0,duration_seconds INTEGER NOT NULL DEFAULT 0,stars INTEGER NOT NULL DEFAULT 0,completed INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
   CREATE TABLE IF NOT EXISTS teachers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
   CREATE TABLE IF NOT EXISTS teacher_classes(teacher_id INTEGER NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,class_id INTEGER NOT NULL REFERENCES classes(id) ON DELETE CASCADE,PRIMARY KEY(teacher_id,class_id));`);
 } const missing=usePostgres?await q('SELECT id,name,code,username,password_hash FROM students WHERE username IS NULL OR password_hash IS NULL'):await q('',[],'SELECT id,name,code,username,password_hash FROM students WHERE username IS NULL OR password_hash IS NULL');
 for(const st of missing){const username=st.username||await uniqueUsername(st.name),password_hash=st.password_hash||hashPassword(st.code);if(usePostgres)await pool.query('UPDATE students SET username=$1,password_hash=$2 WHERE id=$3',[username,password_hash,st.id]);else sqlite.prepare('UPDATE students SET username=?,password_hash=? WHERE id=?').run(username,password_hash,st.id)}

 // v2.6.1: yeni satranç oyunlarını bir kez kütüphaneye ekle.
 const builtins=[['Siyah ve Beyaz Satranç Taşlarını Eşleştir','chess_color_match'],['Satranç Taşları ve Sayıları','chess_count'],['Satranç Taşlarını Düzelt','chess_fix'],['Satrançta Yönleri Öğreniyorum','chess_directions'],['Kalenin Hareketi ve Taş Alması','rook_capture'],['Filin Hareketi ve Taş Alması','bishop_capture'],['Vezirin Hareketi ve Taş Alması','queen_capture'],['Atın Hareketi ve Taş Alması','knight_capture'],['Şahın Hareketi ve Taş Alması','king_capture'],['Piyonun Hareketi ve Taş Alması','pawn_capture']];
 for(const [title,type] of builtins){
  const ex=await one(usePostgres?'SELECT id FROM games WHERE game_type=$1 LIMIT 1':'',[type],'SELECT id FROM games WHERE game_type=? LIMIT 1');
  if(!ex){if(usePostgres)await pool.query('INSERT INTO games(title,canva_url,game_type,game_data) VALUES($1,$2,$3,$4)',[title,'',type,'{}']);else sqlite.prepare('INSERT INTO games(title,canva_url,game_type,game_data) VALUES(?,?,?,?)').run(title,'',type,'{}')}
 }
}
async function q(pg,p=[],sq=pg){return usePostgres?(await pool.query(pg,p)).rows:sqlite.prepare(sq).all(...p)}
async function one(pg,p=[],sq=pg){return usePostgres?(await pool.query(pg,p)).rows[0]:sqlite.prepare(sq).get(...p)}
async function run(pg,p=[],sq=pg){return usePostgres?pool.query(pg,p):sqlite.prepare(sq).run(...p)}
function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((ok,no)=>{let d='';req.on('data',c=>{d+=c;if(d.length>1e6)req.destroy()});req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){no(e)}});req.on('error',no)})}
const teacherSessions=new Map();
function admin(req){return req.headers['x-teacher-password']===TEACHER_PASSWORD}
function teacherSession(req){const tok=String(req.headers['x-teacher-token']||'');const ses=teacherSessions.get(tok);if(!ses)return null;if(Date.now()-ses.created>12*60*60*1000){teacherSessions.delete(tok);return null}return ses}
function teacher(req){return admin(req)||Boolean(teacherSession(req))}
function needTeacher(req,res){if(!teacher(req)){json(res,401,{error:'Öğretmen veya yönetici oturumu gerekli'});return false}return true}
function needAdmin(req,res){if(!admin(req)){json(res,403,{error:'Yönetici yetkisi gerekli'});return false}return true}
function validUrl(v){try{const u=new URL(v);return ['https:'].includes(u.protocol)&&/(^|\.)canva\.com$/i.test(u.hostname)}catch{return false}}
function usernameBase(name){return String(name||'ogrenci').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'.').replace(/^\.+|\.+$/g,'').slice(0,24)||'ogrenci'}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return `${salt}:${crypto.scryptSync(String(password),salt,32).toString('hex')}`}
function verifyPassword(password,stored){try{const [salt,hex]=String(stored||'').split(':');if(!salt||!hex)return false;const a=Buffer.from(hex,'hex'),b=crypto.scryptSync(String(password),salt,a.length);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
async function uniqueUsername(name){const base=usernameBase(name);let u=base,n=1;while(await one(usePostgres?'SELECT 1 FROM students WHERE username=$1':'',[u],'SELECT 1 FROM students WHERE username=?'))u=`${base}.${++n}`;return u}
async function uniqueCode(){let c;do{c=makeCode()}while(await one(usePostgres?'SELECT 1 FROM students WHERE code=$1':'',[c],'SELECT 1 FROM students WHERE code=?'));return c}

async function api(req,res,url){
 try{
  if(req.method==='POST'&&url.pathname==='/api/admin/login'){const b=await body(req);const ok=b.password===TEACHER_PASSWORD;return json(res,ok?200:401,{ok,role:ok?'admin':null})}
  if(req.method==='POST'&&url.pathname==='/api/teacher/login'){const b=await body(req),username=String(b.username||'').trim().toLowerCase(),password=String(b.password||'');const t=usePostgres?await one('SELECT * FROM teachers WHERE LOWER(username)=$1 AND active=TRUE',[username]):await one('',[username],'SELECT * FROM teachers WHERE LOWER(username)=? AND active=1');if(!t||!verifyPassword(password,t.password_hash))return json(res,401,{error:'Kullanıcı adı veya şifre yanlış'});const token=crypto.randomBytes(24).toString('hex');teacherSessions.set(token,{id:Number(t.id),name:t.name,created:Date.now()});return json(res,200,{ok:true,role:'teacher',token,name:t.name})}
  if(req.method==='GET'&&url.pathname==='/api/teachers'){if(!needAdmin(req,res))return;const rows=usePostgres?await q(`SELECT t.id,t.name,t.username,t.active,COALESCE(json_agg(json_build_object('id',c.id,'name',c.name)) FILTER (WHERE c.id IS NOT NULL),'[]') classes FROM teachers t LEFT JOIN teacher_classes tc ON tc.teacher_id=t.id LEFT JOIN classes c ON c.id=tc.class_id GROUP BY t.id ORDER BY t.name`):await q('',[],`SELECT id,name,username,active FROM teachers ORDER BY name`);if(!usePostgres)for(const t of rows)t.classes=await q('',[t.id],`SELECT c.id,c.name FROM teacher_classes tc JOIN classes c ON c.id=tc.class_id WHERE tc.teacher_id=? ORDER BY c.name`);return json(res,200,rows)}
  if(req.method==='POST'&&url.pathname==='/api/teachers'){if(!needAdmin(req,res))return;const b=await body(req),name=String(b.name||'').trim(),username=String(b.username||'').trim().toLowerCase(),password=String(b.password||''),class_ids=Array.isArray(b.class_ids)?b.class_ids.map(Number):[];if(!name||!username||password.length<6)return json(res,400,{error:'Ad, kullanıcı adı ve en az 6 karakter şifre gerekli'});try{let id;if(usePostgres){const r=await pool.query('INSERT INTO teachers(name,username,password_hash) VALUES($1,$2,$3) RETURNING id',[name,username,hashPassword(password)]);id=Number(r.rows[0].id)}else{id=Number(sqlite.prepare('INSERT INTO teachers(name,username,password_hash) VALUES(?,?,?)').run(name,username,hashPassword(password)).lastInsertRowid)}for(const cid of class_ids)await run(usePostgres?'INSERT INTO teacher_classes(teacher_id,class_id) VALUES($1,$2) ON CONFLICT DO NOTHING':'',[id,cid],'INSERT OR IGNORE INTO teacher_classes(teacher_id,class_id) VALUES(?,?)');return json(res,201,{ok:true,id})}catch(e){return json(res,400,{error:'Bu kullanıcı adı kullanılıyor olabilir'})}}
  let tm=url.pathname.match(/^\/api\/teachers\/(\d+)$/);
  if(tm&&req.method==='PATCH'){if(!needAdmin(req,res))return;const id=Number(tm[1]),b=await body(req);if(b.name!==undefined)await run(usePostgres?'UPDATE teachers SET name=$1 WHERE id=$2':'',[String(b.name).trim(),id],'UPDATE teachers SET name=? WHERE id=?');if(b.username!==undefined)await run(usePostgres?'UPDATE teachers SET username=$1 WHERE id=$2':'',[String(b.username).trim().toLowerCase(),id],'UPDATE teachers SET username=? WHERE id=?');if(b.active!==undefined)await run(usePostgres?'UPDATE teachers SET active=$1 WHERE id=$2':'',[Boolean(b.active),id],'UPDATE teachers SET active=? WHERE id=?');if(b.password)await run(usePostgres?'UPDATE teachers SET password_hash=$1 WHERE id=$2':'',[hashPassword(String(b.password)),id],'UPDATE teachers SET password_hash=? WHERE id=?');if(Array.isArray(b.class_ids)){await run(usePostgres?'DELETE FROM teacher_classes WHERE teacher_id=$1':'',[id],'DELETE FROM teacher_classes WHERE teacher_id=?');for(const cid of b.class_ids.map(Number))await run(usePostgres?'INSERT INTO teacher_classes(teacher_id,class_id) VALUES($1,$2) ON CONFLICT DO NOTHING':'',[id,cid],'INSERT OR IGNORE INTO teacher_classes(teacher_id,class_id) VALUES(?,?)')}return json(res,200,{ok:true})}
  if(tm&&req.method==='DELETE'){if(!needAdmin(req,res))return;await run(usePostgres?'DELETE FROM teachers WHERE id=$1':'',[Number(tm[1])],'DELETE FROM teachers WHERE id=?');return json(res,200,{ok:true})}
  if(req.method==='GET'&&url.pathname==='/api/classes'){if(!needTeacher(req,res))return;const r=usePostgres?await q(`SELECT c.*,COUNT(s.id)::int student_count FROM classes c LEFT JOIN students s ON s.class_id=c.id GROUP BY c.id ORDER BY c.name`):await q('',[],`SELECT c.*,COUNT(s.id) student_count FROM classes c LEFT JOIN students s ON s.class_id=c.id GROUP BY c.id ORDER BY c.name`);return json(res,200,r)}
  if(req.method==='POST'&&url.pathname==='/api/classes'){if(!needTeacher(req,res))return;const b=await body(req),name=String(b.name||'').trim();if(!name)return json(res,400,{error:'Sınıf adı gerekli'});try{if(usePostgres){const r=await pool.query('INSERT INTO classes(name) VALUES($1) RETURNING id,name',[name]);return json(res,201,r.rows[0])}const r=sqlite.prepare('INSERT INTO classes(name) VALUES(?)').run(name);return json(res,201,{id:Number(r.lastInsertRowid),name})}catch{return json(res,409,{error:'Bu sınıf zaten var'})}}
  let m=url.pathname.match(/^\/api\/classes\/(\d+)$/);
  if(m&&req.method==='PATCH'){if(!needTeacher(req,res))return;const b=await body(req),name=String(b.name||'').trim();if(!name)return json(res,400,{error:'Sınıf adı gerekli'});try{await run(usePostgres?'UPDATE classes SET name=$1 WHERE id=$2':'',[name,Number(m[1])],'UPDATE classes SET name=? WHERE id=?');return json(res,200,{ok:true})}catch{return json(res,409,{error:'Bu sınıf adı kullanılıyor'})}}
  if(m&&req.method==='DELETE'){if(!needTeacher(req,res))return;await run(usePostgres?'DELETE FROM classes WHERE id=$1':'',[Number(m[1])],'DELETE FROM classes WHERE id=?');return json(res,200,{ok:true})}

  m=url.pathname.match(/^\/api\/classes\/(\d+)\/students$/);
  if(m&&req.method==='GET'){if(!needTeacher(req,res))return;const id=Number(m[1]);const r=usePostgres?await q(`SELECT s.*,COUNT(a.id)::int assigned_count,COUNT(a.completed_at)::int completed_count FROM students s LEFT JOIN assignments a ON a.student_id=s.id WHERE s.class_id=$1 GROUP BY s.id ORDER BY s.name`,[id]):await q('',[id],`SELECT s.*,COUNT(a.id) assigned_count,SUM(CASE WHEN a.completed_at IS NOT NULL THEN 1 ELSE 0 END) completed_count FROM students s LEFT JOIN assignments a ON a.student_id=s.id WHERE s.class_id=? GROUP BY s.id ORDER BY s.name`);return json(res,200,r)}
  if(m&&req.method==='POST'){if(!needTeacher(req,res))return;const b=await body(req),name=String(b.name||'').trim(),guardian_name=String(b.guardian_name||'').trim(),guardian_phone=String(b.guardian_phone||'').trim(),photo_data=String(b.photo_data||''),teacher_note=String(b.teacher_note||'').trim();if(!name)return json(res,400,{error:'Öğrenci adı gerekli'});if(photo_data&&!/^data:image\/(jpeg|png|webp);base64,/i.test(photo_data))return json(res,400,{error:'Geçersiz fotoğraf'});const code=await uniqueCode(),username=await uniqueUsername(name),password_hash=hashPassword(code);if(usePostgres){const r=await pool.query('INSERT INTO students(class_id,name,code,guardian_name,guardian_phone,photo_data,teacher_note,username,password_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,name,code,username',[Number(m[1]),name,code,guardian_name,guardian_phone,photo_data||null,teacher_note,username,password_hash]);return json(res,201,r.rows[0])}const r=sqlite.prepare('INSERT INTO students(class_id,name,code,guardian_name,guardian_phone,photo_data,teacher_note,username,password_hash) VALUES(?,?,?,?,?,?,?,?,?)').run(Number(m[1]),name,code,guardian_name,guardian_phone,photo_data||null,teacher_note,username,password_hash);return json(res,201,{id:Number(r.lastInsertRowid),name,code,username})}
  m=url.pathname.match(/^\/api\/classes\/(\d+)\/students\/bulk$/);
  if(m&&req.method==='POST'){if(!needTeacher(req,res))return;const b=await body(req),names=(Array.isArray(b.names)?b.names:[]).map(x=>String(x).trim()).filter(Boolean).slice(0,100);if(!names.length)return json(res,400,{error:'En az bir öğrenci adı gerekli'});let out=[];for(const name of names){const code=await uniqueCode(),username=await uniqueUsername(name),password_hash=hashPassword(code);if(usePostgres){const r=await pool.query('INSERT INTO students(class_id,name,code,username,password_hash) VALUES($1,$2,$3,$4,$5) RETURNING id,name,code,username',[Number(m[1]),name,code,username,password_hash]);out.push(r.rows[0])}else{const r=sqlite.prepare('INSERT INTO students(class_id,name,code,username,password_hash) VALUES(?,?,?,?,?)').run(Number(m[1]),name,code,username,password_hash);out.push({id:Number(r.lastInsertRowid),name,code,username})}}return json(res,201,out)}

  m=url.pathname.match(/^\/api\/classes\/(\d+)\/students\/bulk-delete$/);
  if(m&&req.method==='POST'){if(!needTeacher(req,res))return;const b=await body(req),cid=Number(m[1]),ids=[...new Set((Array.isArray(b.student_ids)?b.student_ids:[]).map(Number).filter(Number.isFinite))].slice(0,100);if(!ids.length)return json(res,400,{error:'Silinecek öğrenci seçilmedi'});const valid=usePostgres?await q('SELECT id FROM students WHERE class_id=$1 AND id=ANY($2::bigint[])',[cid,ids]):ids.length?await q('',[cid,...ids],`SELECT id FROM students WHERE class_id=? AND id IN (${ids.map(()=>'?').join(',')})`):[];const safeIds=valid.map(x=>Number(x.id));if(!safeIds.length)return json(res,404,{error:'Öğrenci bulunamadı'});if(usePostgres)await pool.query('DELETE FROM students WHERE class_id=$1 AND id=ANY($2::bigint[])',[cid,safeIds]);else sqlite.prepare(`DELETE FROM students WHERE class_id=? AND id IN (${safeIds.map(()=>'?').join(',')})`).run(cid,...safeIds);return json(res,200,{ok:true,deleted:safeIds.length})}

  m=url.pathname.match(/^\/api\/students\/(\d+)$/);
  if(m&&req.method==='PATCH'){if(!needTeacher(req,res))return;const b=await body(req),sid=Number(m[1]);if(b.name!==undefined){const name=String(b.name).trim();if(!name)return json(res,400,{error:'Ad gerekli'});await run(usePostgres?'UPDATE students SET name=$1 WHERE id=$2':'',[name,sid],'UPDATE students SET name=? WHERE id=?')}if(b.class_id!==undefined)await run(usePostgres?'UPDATE students SET class_id=$1 WHERE id=$2':'',[Number(b.class_id),sid],'UPDATE students SET class_id=? WHERE id=?');if(b.guardian_name!==undefined)await run(usePostgres?'UPDATE students SET guardian_name=$1 WHERE id=$2':'',[String(b.guardian_name).trim(),sid],'UPDATE students SET guardian_name=? WHERE id=?');if(b.guardian_phone!==undefined)await run(usePostgres?'UPDATE students SET guardian_phone=$1 WHERE id=$2':'',[String(b.guardian_phone).trim(),sid],'UPDATE students SET guardian_phone=? WHERE id=?');if(b.photo_data!==undefined){const ph=String(b.photo_data||'');if(ph&&!/^data:image\/(jpeg|png|webp);base64,/i.test(ph))return json(res,400,{error:'Geçersiz fotoğraf'});await run(usePostgres?'UPDATE students SET photo_data=$1 WHERE id=$2':'',[ph||null,sid],'UPDATE students SET photo_data=? WHERE id=?')}if(b.teacher_note!==undefined)await run(usePostgres?'UPDATE students SET teacher_note=$1 WHERE id=$2':'',[String(b.teacher_note).trim(),sid],'UPDATE students SET teacher_note=? WHERE id=?');return json(res,200,{ok:true})}
  if(m&&req.method==='DELETE'){if(!needTeacher(req,res))return;await run(usePostgres?'DELETE FROM students WHERE id=$1':'',[Number(m[1])],'DELETE FROM students WHERE id=?');return json(res,200,{ok:true})}
  m=url.pathname.match(/^\/api\/students\/(\d+)\/regenerate-code$/);
  if(m&&req.method==='POST'){if(!needTeacher(req,res))return;const code=await uniqueCode();await run(usePostgres?'UPDATE students SET code=$1 WHERE id=$2':'',[code,Number(m[1])],'UPDATE students SET code=? WHERE id=?');return json(res,200,{code})}
  m=url.pathname.match(/^\/api\/students\/(\d+)\/profile$/);
  if(m&&req.method==='GET'){if(!needTeacher(req,res))return;const sid=Number(m[1]);const s=usePostgres?await one(`SELECT s.*,c.name class_name FROM students s JOIN classes c ON c.id=s.class_id WHERE s.id=$1`,[sid]):await one('',[sid],`SELECT s.*,c.name class_name FROM students s JOIN classes c ON c.id=s.class_id WHERE s.id=?`);if(!s)return json(res,404,{error:'Öğrenci bulunamadı'});const games=usePostgres?await q(`SELECT g.id game_id,g.title,g.canva_url,g.game_type,g.game_data,a.assigned_at,a.completed_at FROM assignments a JOIN games g ON g.id=a.game_id WHERE a.student_id=$1 ORDER BY a.id DESC`,[sid]):await q('',[sid],`SELECT g.id game_id,g.title,g.canva_url,g.game_type,g.game_data,a.assigned_at,a.completed_at FROM assignments a JOIN games g ON g.id=a.game_id WHERE a.student_id=? ORDER BY a.id DESC`);const notes=usePostgres?await q('SELECT id,note,created_at,seen_at FROM parent_notes WHERE student_id=$1 ORDER BY id DESC',[sid]):await q('',[sid],'SELECT id,note,created_at,seen_at FROM parent_notes WHERE student_id=? ORDER BY id DESC');return json(res,200,{student:s,games,parent_notes:notes})}

  m=url.pathname.match(/^\/api\/students\/(\d+)\/parent-notes$/);
  if(m&&req.method==='POST'){if(!needTeacher(req,res))return;const sid=Number(m[1]),b=await body(req),note=String(b.note||'').trim().slice(0,1000);if(!note)return json(res,400,{error:'Veli notu boş olamaz'});if(usePostgres){const r=await pool.query('INSERT INTO parent_notes(student_id,note) VALUES($1,$2) RETURNING *',[sid,note]);return json(res,201,r.rows[0])}const r=sqlite.prepare('INSERT INTO parent_notes(student_id,note) VALUES(?,?)').run(sid,note);return json(res,201,{id:Number(r.lastInsertRowid),note})}
  m=url.pathname.match(/^\/api\/parent-notes\/(\d+)$/);
  if(m&&req.method==='DELETE'){if(!needTeacher(req,res))return;await run(usePostgres?'DELETE FROM parent_notes WHERE id=$1':'',[Number(m[1])],'DELETE FROM parent_notes WHERE id=?');return json(res,200,{ok:true})}

  m=url.pathname.match(/^\/api\/classes\/(\d+)\/meals$/);
  if(m&&req.method==='GET'){if(!needTeacher(req,res))return;const cid=Number(m[1]),date=String(url.searchParams.get('date')||'').slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return json(res,400,{error:'Geçerli tarih gerekli'});const students=usePostgres?await q('SELECT id,name FROM students WHERE class_id=$1 ORDER BY name',[cid]):await q('',[cid],'SELECT id,name FROM students WHERE class_id=? ORDER BY name');const records=usePostgres?await q(`SELECT mr.student_id,mr.meal,mr.status,mr.record_date FROM meal_records mr JOIN students s ON s.id=mr.student_id WHERE s.class_id=$1 AND mr.record_date=$2`,[cid,date]):await q('',[cid,date],`SELECT mr.student_id,mr.meal,mr.status,mr.record_date FROM meal_records mr JOIN students s ON s.id=mr.student_id WHERE s.class_id=? AND mr.record_date=?`);return json(res,200,{students,records})}
  if(m&&req.method==='PUT'){if(!needTeacher(req,res))return;const cid=Number(m[1]),b=await body(req),date=String(b.date||'').slice(0,10),records=Array.isArray(b.records)?b.records:[];if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return json(res,400,{error:'Geçerli tarih gerekli'});const allowedMeals=new Set(['breakfast','lunch','snack']),allowedStatus=new Set(['ate','some','none','absent']);const validStudents=new Set((usePostgres?await q('SELECT id FROM students WHERE class_id=$1',[cid]):await q('',[cid],'SELECT id FROM students WHERE class_id=?')).map(x=>Number(x.id)));if(usePostgres)await pool.query(`DELETE FROM meal_records mr USING students s WHERE mr.student_id=s.id AND s.class_id=$1 AND mr.record_date=$2`,[cid,date]);else sqlite.prepare(`DELETE FROM meal_records WHERE record_date=? AND student_id IN (SELECT id FROM students WHERE class_id=?)`).run(date,cid);for(const r of records){const sid=Number(r.student_id),meal=String(r.meal||''),status=String(r.status||'');if(!validStudents.has(sid)||!allowedMeals.has(meal)||!allowedStatus.has(status))continue;if(usePostgres)await pool.query(`INSERT INTO meal_records(student_id,record_date,meal,status) VALUES($1,$2,$3,$4) ON CONFLICT(student_id,record_date,meal) DO UPDATE SET status=EXCLUDED.status,updated_at=NOW()`,[sid,date,meal,status]);else sqlite.prepare(`INSERT INTO meal_records(student_id,record_date,meal,status) VALUES(?,?,?,?) ON CONFLICT(student_id,record_date,meal) DO UPDATE SET status=excluded.status,updated_at=CURRENT_TIMESTAMP`).run(sid,date,meal,status)}return json(res,200,{ok:true})}

  if(req.method==='GET'&&url.pathname==='/api/games'){if(!needTeacher(req,res))return;const r=usePostgres?await q(`SELECT g.*,COUNT(a.id)::int assigned_count,COUNT(a.completed_at)::int completed_count FROM games g LEFT JOIN assignments a ON a.game_id=g.id GROUP BY g.id ORDER BY g.id DESC`):await q('',[],`SELECT g.*,COUNT(a.id) assigned_count,SUM(CASE WHEN a.completed_at IS NOT NULL THEN 1 ELSE 0 END) completed_count FROM games g LEFT JOIN assignments a ON a.game_id=g.id GROUP BY g.id ORDER BY g.id DESC`);return json(res,200,r)}
  if(req.method==='POST'&&url.pathname==='/api/games'){if(!needTeacher(req,res))return;const b=await body(req),title=String(b.title||'').trim(),type=['matching','chess_intro','chess_names','chess_setup','atelier_matching','classification','comparison','ordering','chess_color_match','chess_count','chess_fix','chess_directions','rook_capture','bishop_capture','queen_capture','knight_capture','king_capture','pawn_capture'].includes(b.game_type)?b.game_type:'external',canva=String(b.canva_url||'').trim();let gd=null;if(!title)return json(res,400,{error:'Oyun adı gerekli'});if(type==='external'&&!validUrl(canva))return json(res,400,{error:'Geçerli Canva bağlantısı gerekli'});if(type==='matching'){const pairs=Array.isArray(b.pairs)?b.pairs.map(x=>[String(x?.[0]||'').trim(),String(x?.[1]||'').trim()]).filter(x=>x[0]&&x[1]).slice(0,12):[];if(pairs.length<2)return json(res,400,{error:'Eşleştirme oyunu için en az 2 çift gerekli'});gd=JSON.stringify({pairs})}if(['atelier_matching','classification','comparison','ordering','chess_color_match','chess_count','chess_fix','chess_directions','rook_capture','bishop_capture','queen_capture','knight_capture','king_capture','pawn_capture'].includes(type)){const cfg=(b.game_data&&typeof b.game_data==='object')?b.game_data:{};gd=JSON.stringify(cfg)}if(usePostgres){const r=await pool.query('INSERT INTO games(title,canva_url,game_type,game_data) VALUES($1,$2,$3,$4) RETURNING *',[title,type==='external'?canva:'',type,gd]);return json(res,201,r.rows[0])}const r=sqlite.prepare('INSERT INTO games(title,canva_url,game_type,game_data) VALUES(?,?,?,?)').run(title,type==='external'?canva:'',type,gd);return json(res,201,{id:Number(r.lastInsertRowid),title,canva_url:type==='external'?canva:'',game_type:type,game_data:gd})}
  m=url.pathname.match(/^\/api\/games\/(\d+)$/);
  if(m&&req.method==='PATCH'){if(!needTeacher(req,res))return;const b=await body(req),gid=Number(m[1]),title=String(b.title||'').trim(),type=['matching','chess_intro','chess_names','chess_setup','atelier_matching','classification','comparison','ordering','chess_color_match','chess_count','chess_fix','chess_directions','rook_capture','bishop_capture','queen_capture','knight_capture','king_capture','pawn_capture'].includes(b.game_type)?b.game_type:'external',canva=String(b.canva_url||'').trim();let gd=null;if(!title)return json(res,400,{error:'Oyun adı gerekli'});if(type==='external'&&!validUrl(canva))return json(res,400,{error:'Geçerli Canva bağlantısı gerekli'});if(type==='matching'){const pairs=Array.isArray(b.pairs)?b.pairs.map(x=>[String(x?.[0]||'').trim(),String(x?.[1]||'').trim()]).filter(x=>x[0]&&x[1]).slice(0,12):[];if(pairs.length<2)return json(res,400,{error:'En az 2 eşleştirme çifti gerekli'});gd=JSON.stringify({pairs})}if(['atelier_matching','classification','comparison','ordering','chess_color_match','chess_count','chess_fix','chess_directions','rook_capture','bishop_capture','queen_capture','knight_capture','king_capture','pawn_capture'].includes(type)){const cfg=(b.game_data&&typeof b.game_data==='object')?b.game_data:{};gd=JSON.stringify(cfg)}await run(usePostgres?'UPDATE games SET title=$1,canva_url=$2,game_type=$3,game_data=$4 WHERE id=$5':'',[title,type==='external'?canva:'',type,gd,gid],'UPDATE games SET title=?,canva_url=?,game_type=?,game_data=? WHERE id=?');return json(res,200,{ok:true})}
  if(m&&req.method==='DELETE'){if(!needTeacher(req,res))return;await run(usePostgres?'DELETE FROM games WHERE id=$1':'',[Number(m[1])],'DELETE FROM games WHERE id=?');return json(res,200,{ok:true})}

  m=url.pathname.match(/^\/api\/games\/(\d+)\/assignment-students$/);
  if(m&&req.method==='GET'){if(!needTeacher(req,res))return;const gid=Number(m[1]),cid=Number(url.searchParams.get('class_id'));const r=usePostgres?await q(`SELECT s.id,s.name,s.code,(a.id IS NOT NULL) assigned,(a.completed_at IS NOT NULL) completed FROM students s LEFT JOIN assignments a ON a.student_id=s.id AND a.game_id=$1 WHERE s.class_id=$2 ORDER BY s.name`,[gid,cid]):await q('',[gid,cid],`SELECT s.id,s.name,s.code,(a.id IS NOT NULL) assigned,(a.completed_at IS NOT NULL) completed FROM students s LEFT JOIN assignments a ON a.student_id=s.id AND a.game_id=? WHERE s.class_id=? ORDER BY s.name`);return json(res,200,r)}
  if(m&&req.method==='PUT'){if(!needTeacher(req,res))return;const gid=Number(m[1]),b=await body(req),cid=Number(b.class_id),ids=[...new Set((b.student_ids||[]).map(Number).filter(Number.isFinite))];const valid=(usePostgres?await q('SELECT id FROM students WHERE class_id=$1',[cid]):await q('',[cid],'SELECT id FROM students WHERE class_id=?')).map(x=>Number(x.id));const selected=ids.filter(x=>valid.includes(x));const current=usePostgres?await q(`SELECT a.student_id,a.completed_at FROM assignments a JOIN students s ON s.id=a.student_id WHERE a.game_id=$1 AND s.class_id=$2`,[gid,cid]):await q('',[gid,cid],`SELECT a.student_id,a.completed_at FROM assignments a JOIN students s ON s.id=a.student_id WHERE a.game_id=? AND s.class_id=?`);const cur=new Map(current.map(x=>[Number(x.student_id),x.completed_at]));for(const sid of selected)if(!cur.has(sid)){if(usePostgres)await pool.query('INSERT INTO assignments(game_id,student_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[gid,sid]);else sqlite.prepare('INSERT OR IGNORE INTO assignments(game_id,student_id) VALUES(?,?)').run(gid,sid)}for(const [sid,completed] of cur)if(!selected.includes(sid)){if(completed)return json(res,409,{error:'Tamamlamış bir öğrenci atamadan çıkarılamaz. Önce kaydını koruyarak bırakmalısın.'});if(usePostgres)await pool.query('DELETE FROM assignments WHERE game_id=$1 AND student_id=$2',[gid,sid]);else sqlite.prepare('DELETE FROM assignments WHERE game_id=? AND student_id=?').run(gid,sid)}return json(res,200,{ok:true})}

  m=url.pathname.match(/^\/api\/classes\/(\d+)\/assignments$/);
  if(m&&req.method==='GET'){if(!needTeacher(req,res))return;const cid=Number(m[1]);const r=usePostgres?await q(`SELECT g.id game_id,g.title,g.canva_url,s.id student_id,s.name,s.code,a.completed_at,a.assigned_at FROM assignments a JOIN games g ON g.id=a.game_id JOIN students s ON s.id=a.student_id WHERE s.class_id=$1 ORDER BY g.id DESC,s.name`,[cid]):await q('',[cid],`SELECT g.id game_id,g.title,g.canva_url,s.id student_id,s.name,s.code,a.completed_at,a.assigned_at FROM assignments a JOIN games g ON g.id=a.game_id JOIN students s ON s.id=a.student_id WHERE s.class_id=? ORDER BY g.id DESC,s.name`);return json(res,200,r)}

  if(req.method==='POST'&&url.pathname==='/api/student/login'){const b=await body(req),username=String(b.username||'').trim().toLowerCase(),password=String(b.password||'');if(!username||!password)return json(res,400,{error:'Kullanıcı adı ve şifre gerekli'});const st=usePostgres?await one(`SELECT s.id,s.name,s.code,s.username,s.password_hash,s.password_changed,s.photo_data,c.name class_name FROM students s JOIN classes c ON c.id=s.class_id WHERE LOWER(s.username)=$1`,[username]):await one('',[username],`SELECT s.id,s.name,s.code,s.username,s.password_hash,s.password_changed,s.photo_data,c.name class_name FROM students s JOIN classes c ON c.id=s.class_id WHERE LOWER(s.username)=?`);if(!st||!verifyPassword(password,st.password_hash))return json(res,401,{error:'Kullanıcı adı veya şifre yanlış'});delete st.password_hash;return json(res,200,st)}
  m=url.pathname.match(/^\/api\/student\/(\d+)\/password$/);
  if(m&&req.method==='POST'){const sid=Number(m[1]),code=String(req.headers['x-student-code']||'').toUpperCase(),b=await body(req),oldp=String(b.old_password||''),newp=String(b.new_password||'');if(newp.length<4)return json(res,400,{error:'Yeni şifre en az 4 karakter olmalı'});const st=usePostgres?await one('SELECT code,password_hash FROM students WHERE id=$1 AND code=$2',[sid,code]):await one('',[sid,code],'SELECT code,password_hash FROM students WHERE id=? AND code=?');if(!st)return json(res,401,{error:'Geçersiz öğrenci erişimi'});if(!verifyPassword(oldp,st.password_hash))return json(res,401,{error:'Mevcut şifre yanlış'});const ph=hashPassword(newp);await run(usePostgres?'UPDATE students SET password_hash=$1,password_changed=TRUE WHERE id=$2':'',[ph,sid],'UPDATE students SET password_hash=?,password_changed=1 WHERE id=?');return json(res,200,{ok:true})}
  m=url.pathname.match(/^\/api\/student\/(\d+)\/games$/);
  if(m&&req.method==='GET'){const sid=Number(m[1]),code=String(req.headers['x-student-code']||'').toUpperCase();const ok=usePostgres?await one('SELECT 1 FROM students WHERE id=$1 AND code=$2',[sid,code]):await one('',[sid,code],'SELECT 1 FROM students WHERE id=? AND code=?');if(!ok)return json(res,401,{error:'Geçersiz öğrenci erişimi'});const r=usePostgres?await q(`SELECT a.id assignment_id,g.title,g.canva_url,g.game_type,g.game_data,a.completed_at,a.assigned_at FROM assignments a JOIN games g ON g.id=a.game_id WHERE a.student_id=$1 ORDER BY a.id DESC`,[sid]):await q('',[sid],`SELECT a.id assignment_id,g.title,g.canva_url,g.game_type,g.game_data,a.completed_at,a.assigned_at FROM assignments a JOIN games g ON g.id=a.game_id WHERE a.student_id=? ORDER BY a.id DESC`);return json(res,200,r)}
  m=url.pathname.match(/^\/api\/student\/(\d+)\/parent-notes$/);
  if(m&&req.method==='GET'){const sid=Number(m[1]),code=String(req.headers['x-student-code']||'').toUpperCase();const ok=usePostgres?await one('SELECT 1 FROM students WHERE id=$1 AND code=$2',[sid,code]):await one('',[sid,code],'SELECT 1 FROM students WHERE id=? AND code=?');if(!ok)return json(res,401,{error:'Geçersiz öğrenci erişimi'});const r=usePostgres?await q('SELECT id,note,created_at,seen_at FROM parent_notes WHERE student_id=$1 ORDER BY id DESC',[sid]):await q('',[sid],'SELECT id,note,created_at,seen_at FROM parent_notes WHERE student_id=? ORDER BY id DESC');if(usePostgres)await pool.query('UPDATE parent_notes SET seen_at=COALESCE(seen_at,NOW()) WHERE student_id=$1',[sid]);else sqlite.prepare("UPDATE parent_notes SET seen_at=COALESCE(seen_at,datetime('now')) WHERE student_id=?").run(sid);return json(res,200,r)}
  m=url.pathname.match(/^\/api\/student\/(\d+)\/meals$/);
  if(m&&req.method==='GET'){const sid=Number(m[1]),code=String(req.headers['x-student-code']||'').toUpperCase();const ok=usePostgres?await one('SELECT 1 FROM students WHERE id=$1 AND code=$2',[sid,code]):await one('',[sid,code],'SELECT 1 FROM students WHERE id=? AND code=?');if(!ok)return json(res,401,{error:'Geçersiz öğrenci erişimi'});const today=String(url.searchParams.get('date')||new Date().toISOString().slice(0,10)).slice(0,10);const r=usePostgres?await q('SELECT meal,status,record_date FROM meal_records WHERE student_id=$1 AND record_date=$2 ORDER BY CASE meal WHEN \'breakfast\' THEN 1 WHEN \'lunch\' THEN 2 ELSE 3 END',[sid,today]):await q('',[sid,today],`SELECT meal,status,record_date FROM meal_records WHERE student_id=? AND record_date=? ORDER BY CASE meal WHEN 'breakfast' THEN 1 WHEN 'lunch' THEN 2 ELSE 3 END`);return json(res,200,r)}
  m=url.pathname.match(/^\/api\/assignments\/(\d+)\/attempt$/);
  if(m&&req.method==='POST'){const aid=Number(m[1]),code=String(req.headers['x-student-code']||'').toUpperCase(),b=await body(req);const ass=usePostgres?await one(`SELECT a.id FROM assignments a JOIN students s ON s.id=a.student_id WHERE a.id=$1 AND s.code=$2`,[aid,code]):await one('',[aid,code],`SELECT a.id FROM assignments a JOIN students s ON s.id=a.student_id WHERE a.id=? AND s.code=?`);if(!ass)return json(res,401,{error:'Yetkisiz'});const first=Math.max(0,Number(b.first_score)||0),total=Math.max(1,Number(b.total)||1),retries=Math.max(0,Number(b.retries)||0),duration=Math.max(0,Number(b.duration_seconds)||0),stars=Math.max(0,Math.min(3,Number(b.stars)||0)),completed=!!b.completed;if(usePostgres)await pool.query('INSERT INTO game_attempts(assignment_id,first_score,total,retries,duration_seconds,stars,completed) VALUES($1,$2,$3,$4,$5,$6,$7)',[aid,first,total,retries,duration,stars,completed]);else sqlite.prepare('INSERT INTO game_attempts(assignment_id,first_score,total,retries,duration_seconds,stars,completed) VALUES(?,?,?,?,?,?,?)').run(aid,first,total,retries,duration,stars,completed?1:0);return json(res,200,{ok:true})}
  m=url.pathname.match(/^\/api\/students\/(\d+)\/performance$/);
  if(m&&req.method==='GET'){if(!needTeacher(req,res))return;const sid=Number(m[1]);const r=usePostgres?await q(`SELECT ga.*,g.title,g.game_type,g.game_data FROM game_attempts ga JOIN assignments a ON a.id=ga.assignment_id JOIN games g ON g.id=a.game_id WHERE a.student_id=$1 ORDER BY ga.id DESC`,[sid]):await q('',[sid],`SELECT ga.*,g.title,g.game_type,g.game_data FROM game_attempts ga JOIN assignments a ON a.id=ga.assignment_id JOIN games g ON g.id=a.game_id WHERE a.student_id=? ORDER BY ga.id DESC`);return json(res,200,r)}
  m=url.pathname.match(/^\/api\/assignments\/(\d+)\/complete$/);
  if(m&&req.method==='POST'){const aid=Number(m[1]),code=String(req.headers['x-student-code']||'').toUpperCase();const a=usePostgres?await one(`SELECT a.id FROM assignments a JOIN students s ON s.id=a.student_id WHERE a.id=$1 AND s.code=$2`,[aid,code]):await one('',[aid,code],`SELECT a.id FROM assignments a JOIN students s ON s.id=a.student_id WHERE a.id=? AND s.code=?`);if(!a)return json(res,401,{error:'Yetkisiz'});await run(usePostgres?'UPDATE assignments SET completed_at=COALESCE(completed_at,NOW()) WHERE id=$1':'',[aid],"UPDATE assignments SET completed_at=COALESCE(completed_at,datetime('now')) WHERE id=?");return json(res,200,{ok:true})}
  return json(res,404,{error:'Bulunamadı'});
 }catch(e){console.error(e);return json(res,500,{error:'Sunucu hatası'})}
}
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return api(req,res,url);let p=url.pathname==='/'?'/index.html':url.pathname;p=path.normalize(p).replace(/^\.\.(\/|\\|$)/,'');const file=path.join(__dirname,'public',p);if(!file.startsWith(path.join(__dirname,'public'))){res.writeHead(403);return res.end('Forbidden')}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':path.extname(file)==='.html'?'no-cache':'public, max-age=300','X-Content-Type-Options':'nosniff'});res.end(data)})});
initDb().then(()=>server.listen(PORT,()=>console.log(`Minoo v2.6.3: http://localhost:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
